### PR TITLE
Story/webtlkt 1624 sync upstream 2.6.2

### PR DESCRIPTION
**Pull request by thescientist13**
## Ticket
https://jira.clarivate.io/browse/WEBTLKT-1624

## Summary of Changes
1. Documented development and upstream sychronization workflows
1. Create an automated release script for making a release
1. Following new workflow, created this branch off of `master` and merged in the `2.6.2` tag from upstream Snowplow

## Notes
I tested the script locally, but will formally cut the release after this OR gets merged, e.g
  - Create the `2.6.2-clv` release
  - Open the PNAS ticket
  - Update / test in **webui-component-analytics**

### CODE REVIEW

**Comment by maksimlikharev** [comment]
don't see our session accessor change, may be it is there, could you please double check

**Comment by thescientist13** [comment]
@maksimlikharev 
Could you be more specific?  Which commit / method / etc are you referring to?

**Comment by thescientist13** [comment]
@maksimlikharev 
Ah, I think I see what you mean.  

For me the diff for _tracker.js_ was collapsed by GitHub, but since these are only upstream changes, it won't appear as a diff in the PR (since master is already is the source of truth for our internal changes.

That said, here is a [link to that method in question in the branch](https://github.com/ThomsonReuters-IPS/snowplow-javascript-tracker/blob/e2590ec955b5dfae2f4c9e9457b7e0640508bd88/src/js/tracker.js#L642) of this PR, so it looks like our changes are intact 💯 

Let me know if there's anything else to double check!  I'm going to do a quick sanity / regression test of these changes against the Analytics component reference app

**Comment by thescientist13** [comment]
@maksimlikharev 
I did some more [testing in the Analytics Component](https://github.com/ThomsonReuters-IPS/webui-component-analytics/pull/55/),  no smoke, so hopefully no fire.  

Will probably merge this soon so I can turn around and ask PNAS to upload the new release of this so AWS so it can start getting tested by WoS team (end of day handoff for today)

**Pull request merged**
